# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[('RePKG.exe', '.')],
    datas=[('icon.ico', '.')],
    hiddenimports=[
        'ttkbootstrap',
        'ttkbootstrap.constants',
        'ttkbootstrap.themes',
        'ttkbootstrap.style',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'tkinter',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'tkinter.ttk',
        'configparser',
        'webbrowser',
        'subprocess',
        'datetime',
        'threading',
        'queue',
        'json',
        'urllib',
        'urllib.request',
        'repkg_ui',
        'repkg_ui.core',
        'repkg_ui.core.config',
        'repkg_ui.core.file_utils',
        'repkg_ui.core.repkg_runner',
        'repkg_ui.ui',
        'repkg_ui.ui.dialogs',
        'repkg_ui.ui.main_window',
        'repkg_ui.ui.styles',
        'repkg_ui.constants'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy',
        'scipy',
        'pandas',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'tornado',
        'zmq'
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='RePKG_UI',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico',
    version='version_info.py',
    uac_admin=False,
    uac_uiaccess=False,
    manifest=None,
    windowed=True,
    onefile=True,
)